#%RAML 1.0 DataType
type: object
description : Ping Response
properties:	
  status:
    description: "It defines the status"
    type: "string"
    example: "200"
  message:
    description: "It gives the status message"
    type: "string"
    example: "Avaliable"
  service:
    description: "API Name"
    type: "string"
    example: "pega-exp-api"

    